### ISSUE TITLE
(GET) The system must allow users to fetch all client records.

### ISSUE THREAD

**Issue by Githubjael** [Jasper85125/Werehouses#22]
Acceptance criteria:

- has a unit test for this process
- commentary explaining snippets that are difficult to understand
- has to be reviewed by at least one other teammate

**Comment by Jasper85125** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(GET) The system must allow users to fetch a specific client record by its ID.](https://trello.com/c/S5jmmOjm/62-get-the-system-must-allow-users-to-fetch-a-specific-client-record-by-its-id)
