### ISSUE TITLE
(POST)The system must support bulk posts of item_types records based on specified conditions.

### ISSUE THREAD

**Issue by Hadyalt** [Jasper85125/Werehouses#271]

**Comment by Stelau1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(POST)The system must support bulk posts of item_types records based on specified conditions.](https://trello.com/c/3gLuivKH/111-postthe-system-must-support-bulk-posts-of-itemtypes-records-based-on-specified-conditions)
